---
- name: Install Packages and start services
  hosts: all
  become: true
  gather_facts: false

  tasks: 

    - name: Install packages
      yum:
        name: 
          - firewalld
          - mariadb
          - mariadb-server
          - tmux
          - tree
          - httpd
          - bash-completion
        state: present

    - name: Start services
      service: 
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - mariadb
        - firewalld

