---
- name: Add some firewall rules
  hosts: all
  become: true

  tasks: 

    - name: Add firewall rules to firewalld
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - httpd
        - mariadb
        
