---
- name: A simple playbook to create an EC2 instance on AWS
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Create a basic AWS ec2 instance
      amazon.aws.ec2_instance:
        key_name: "{{ ec2_key_pair }}"
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_image_id }}"
        wait: true
        security_group: "{{ ec2_sg }}"
        count: "{{ ec2_instance_count }}"
        vpc_subnet_id: "{{ ec2_subnet_id }}"
        region: "{{ ec2_region }}"
        name: "{{ ec2_instance_name }}"
