---
- name: A simple playbook to remove an EC2 instance on AWS
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - snow_vars.yml

  tasks:

    - name: Show Instance name
      debug:
        msg: "{{ ec2_instance_name }}"

    - name: Show SNOW Record
      debug:
        msg: "{{ snow_ticket_num }}"

    - name: Show sysid
      debug:
        msg: "{{ snow_ticket_num }}"

    - name: Remove an existing AWS ec2 instance
      amazon.aws.ec2_instance:
        state: absent
        filters: 
          "tag:Name": "{{ ec2_instance_name }}"
        region: us-east-1
      register: ec2_output

    - name: Return results
      debug: 
        var: ec2_output

    - name: Retrieve all hardare configuration items
      servicenow.itsm.configuration_item_info:
        sys_class_name: cmdb_ci_server
        query:
          - category: = Hardware
      register: the_server

    - name: Remove the EC2 instance from the CMDB
      servicenow.itsm.configuration_item:
        state: absent
        name: "{{ ec2_instance_name }}"
        sys_class_name: cmdb_ci_server
        sys_id: "{{ sys_id }}"
        instance: 
          host: "https://{{ sn_instance }}.service-now.com"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"

    - name: Update a catalog work notes and state in ServiceNow
      servicenow.servicenow.snow_record:
        state: present
        number: "{{ snow_ticket_num }}"
        table: sc_request
        instance: "{{ sn_instance }}"
        username: "{{ sn_username }}"
        password: "{{ sn_password }}"
        data:
          request_state: "Closed Complete"
          work_notes: "EC2 instance {{ ec2_instance_name }} has been removed from AWS and the CMDB"
      when: snow_ticket_num != ''
